### ISSUE TITLE
Doesn't compile on stable 1.65 on the 1st of December 2022

### ISSUE THREAD

**Issue by edgarogh** [remi-dupre/aoc#21]
It seems like an issue with your version on clap.

```
error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/aoc-main-0.3.0/src/lib.rs:23:18
   |
23 |                 .about("Read input from stdin instead of downloading it"),
   |                  ^^^^^ method not found in `Arg<'_>`


error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/aoc-main-0.3.0/src/lib.rs:32:18
   |
32 |                 .about("Read input from file instead of downloading it"),
   |                  ^^^^^ method not found in `Arg<'_>`


error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/aoc-main-0.3.0/src/lib.rs:40:18
   |
40 |                 .about("Days to execute. By default all implemented days will run"),
   |                  ^^^^^ method not found in `Arg<'_>`


error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/aoc-main-0.3.0/src/lib.rs:46:18
   |
46 |                 .about("Run criterion benchmarks"),
   |                  ^^^^^ method not found in `Arg<'_>`
```

**Comment by edgarogh** [comment]
I just saw that this was fixed by afe872ae1bcd83ed4726ffb7e017b4b9339ff9a9, but it looks like the fixed version isn't on crates.io.

**Comment by remi-dupre** [comment]
I've just published a new version to crates.io, hopefully this fixes your issue (in the meantime clap has been updated too, that makes me confident).
